### ISSUE TITLE
Having a weird issue where the current working directory is not in the path for dlhpcstarter:

### ISSUE THREAD

**Issue by anicolson** [csiro-mlai/dl_hpc_starter_pack#8]
```
(simplified_22) bracewell-i1 simplified_22$ dlhpcstarter -t cifar10 -c baseline
Initial utilisation on GPU:0 is 0.057.
Initial utilisation on GPU:1 is 0.990.
Initial utilisation on GPU:2 is 0.288.
Initial utilisation on GPU:3 is 0.411.
Traceback (most recent call last):
  File "/scratch2/nic261/environments/simplified_22/bin/dlhpcstarter", line 8, in <module>
    sys.exit(main())
  File "/scratch2/nic261/environments/simplified_22/lib/python3.9/site-packages/dlhpcstarter/__main__.py", line 37, in main
    stages_fnc = importer(definition='stages', module='.'.join(['task', args.task, 'stages']))
  File "/scratch2/nic261/environments/simplified_22/lib/python3.9/site-packages/dlhpcstarter/utils.py", line 46, in importer
    module = importlib.import_module(module)
  File "/apps/python/3.9.4/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'task'
(simplified_22) bracewell-i1 simplified_22$
```

i.e. it cannot see the task directory

```
(simplified_22) bracewell-i1 simplified_22$ ls
README.md  jobs.sh  main.py  notes.txt  requirements.txt  task  tools
(simplified_22) bracewell-i1 simplified_22$
```

@ashgillman thoughts?

**Comment by anicolson** [comment]
May have something to do with https://github.com/microsoft/debugpy/issues/759

**Comment by anicolson** [comment]
working directory is not in `sys.path`

**Comment by anicolson** [comment]
https://stackoverflow.com/questions/25085346/why-sys-path-doesnt-contain-cwd

**Comment by anicolson** [comment]
is:
```
import sys

if sys.path[0] != '':
    sys.path.insert(0, '')
```
a dodgy solution @ashgillman ?

This works, just wondering if there is a more elegant solution. Is it an issue with where `__main__.py` is placed?

**Comment by ashgillman** [comment]
A few thoughts here, probably in order of worst to best.

As you flag, you can just add the directory to the path. This is probably better/more flexible, as maybe you don't want to hard-code that the directory has to be "tasks", and it could be passed as an argument. Then you can add that directory to sys.path.

Slightly better, we don't necessarily want to import this file as a typical module - we just want the function.
The Python lib has a recommendation for just importing a file here:
https://docs.python.org/3/library/importlib.html#importing-a-source-file-directly

But - this stages.py file was something I was wondering about as I was looking over the code. Its a little less elegant (although perfectly valid if you truly want to give the user a lot of power) to ask the user to write a function. And the stages.py in `tasks` is quite generic. Why not have `stages_fnc` defined in the library?

**Comment by anicolson** [comment]
> As you flag, you can just add the directory to the path. This is probably better/more flexible, as maybe you don't want to hard-code that the directory has to be "tasks", and it could be passed as an argument. Then you can add that directory to sys.path.

Yes, this would be great and in line with: https://github.com/csiro-mlai/dl_hpc_starter_pack/issues/5 (not saying that what is in that issue is a good idea, but saying that the user should have more freedom to define the structure and placement of directories and files in their project).

> Slightly better, we don't necessarily want to import this file as a typical module - we just want the function.
> The Python lib has a recommendation for just importing a file here:
> https://docs.python.org/3/library/importlib.html#importing-a-source-file-directly

Are you referring to `stages.py` here? importlib is used here: https://github.com/csiro-mlai/dl_hpc_starter_pack/blob/af842a18edf2bc61b16c23ea44bb187f6d080c48/src/dlhpcstarter/utils.py#L14. So the user has to point us to the stages function?

> But - this stages.py file was something I was wondering about as I was looking over the code. Its a little less elegant (although perfectly valid if you truly want to give the user a lot of power) to ask the user to write a function. And the stages.py in tasks is quite generic. Why not have stages_fnc defined in the library?

Yes, I think it would be great to have a default stages function. There are cases though where a non-standard model development path is needed (a simple example would be two stages of training), so the flexibility to use a default stages function as well as a user-defined stages function would be great. So, the default stages function is used unless the user defines one and lets the package know somehow (i.e., another argument in config most likely).

**Comment by ashgillman** [comment]
> Are you referring to stages.py here? importlib is used here: 

Yep, but I was referring to this snipped, linked, that specifically imports a file.
```
spec = importlib.util.spec_from_file_location(module_name, file_path)
module = importlib.util.module_from_spec(spec)
sys.modules[module_name] = module
spec.loader.exec_module(module)
```

I think this is a bit nicer than modifying sys.path
